[project]
authors = ["Emmanuelle Sarrazin <emmanuelle.sarrazin@cnes.fr>"]
channels = ["conda-forge"]
description = "Xarray cookbook"
name = "xarray-cookbook"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.0,<26"
numpy = ">=2.2.2,<3"
jupyterlab = ">=4.3.5,<5"
matplotlib = ">=3.10.0,<4"
xarray = ">=2025.1.2,<2026"
h5netcdf = ">=1.5.0,<2"
pandas = ">=2.2.3,<3"
pyarrow = ">=19.0.1,<20"
pooch = ">=1.8.2,<2"
scipy = ">=1.15.2,<2"
netcdf4 = ">=1.7.2,<2"

